export const els = {
  pdfInput: document.getElementById("pdfInput"),
  pdfDrop: document.getElementById("pdfDrop"),
  pdfDropText: document.getElementById("pdfDropText"),
  stampInput: document.getElementById("stampInput"),
  esignInput: document.getElementById("esignInput"),
  includeDate: document.getElementById("includeDate"),
  includeSeparator: document.getElementById("includeSeparator"),
  dateFormat: document.getElementById("dateFormat"),
  openComposerBtn: document.getElementById("openComposerBtn"),
  composerModal: document.getElementById("composerModal"),
  closeComposerBtn: document.getElementById("closeComposerBtn"),
  composerPreview: document.getElementById("composerPreview"),
  layerEditor: document.getElementById("layerEditor"),
  clearPlacementsBtn: document.getElementById("clearPlacementsBtn"),
  exportBtn: document.getElementById("exportBtn"),
  statusEl: document.getElementById("status"),
  fitViewToggle: document.getElementById("fitViewToggle"),
  prevPageBtn: document.getElementById("prevPageBtn"),
  nextPageBtn: document.getElementById("nextPageBtn"),
  pageInfo: document.getElementById("pageInfo"),
  pdfStage: document.getElementById("pdfStage"),
  pdfCanvas: document.getElementById("pdfCanvas"),
  overlay: document.getElementById("overlay"),
  signCanvas: document.getElementById("signCanvas"),
  clearSignBtn: document.getElementById("clearSignBtn"),
  useSignDrawingBtn: document.getElementById("useSignDrawingBtn"),
};

export const pdfCtx = els.pdfCanvas.getContext("2d");
export const signCtx = els.signCanvas.getContext("2d");
