export const els = {
  pdfInput: document.getElementById("pdfInput"),
  pdfDrop: document.getElementById("pdfDrop"),
  pdfDropText: document.getElementById("pdfDropText"),
  clearPdfBtn: document.getElementById("clearPdfBtn"),
  stampDrop: document.getElementById("stampDrop"),
  stampDropText: document.getElementById("stampDropText"),
  stampInput: document.getElementById("stampInput"),
  clearStampBtn: document.getElementById("clearStampBtn"),
  signInputSwitch: document.getElementById("signInputSwitch"),
  signAttachmentPane: document.getElementById("signAttachmentPane"),
  signDrawingPane: document.getElementById("signDrawingPane"),
  signPenStyleGroup: document.getElementById("signPenStyleGroup"),
  esignDrop: document.getElementById("esignDrop"),
  esignDropText: document.getElementById("esignDropText"),
  esignInput: document.getElementById("esignInput"),
  clearEsignBtn: document.getElementById("clearEsignBtn"),
  includeDate: document.getElementById("includeDate"),
  includeSeparator: document.getElementById("includeSeparator"),
  dateFormat: document.getElementById("dateFormat"),
  penColorChoices: document.getElementById("penColorChoices"),
  penSaturation: document.getElementById("penSaturation"),
  penSaturationValue: document.getElementById("penSaturationValue"),
  dateFontFamily: document.getElementById("dateFontFamily"),
  dateFontWeight: document.getElementById("dateFontWeight"),
  dateColorChoices: document.getElementById("dateColorChoices"),
  dateSaturation: document.getElementById("dateSaturation"),
  dateSaturationValue: document.getElementById("dateSaturationValue"),
  openComposerBtn: document.getElementById("openComposerBtn"),
  composerModal: document.getElementById("composerModal"),
  closeComposerBtn: document.getElementById("closeComposerBtn"),
  composerPreview: document.getElementById("composerPreview"),
  layerEditor: document.getElementById("layerEditor"),
  clearPlacementsBtn: document.getElementById("clearPlacementsBtn"),
  exportBtn: document.getElementById("exportBtn"),
  statusEl: document.getElementById("status"),
  fitViewToggle: document.getElementById("fitViewToggle"),
  redactionToggleBtn: document.getElementById("redactionToggleBtn"),
  prevPageBtn: document.getElementById("prevPageBtn"),
  nextPageBtn: document.getElementById("nextPageBtn"),
  pageInfo: document.getElementById("pageInfo"),
  pdfStage: document.getElementById("pdfStage"),
  pdfCanvas: document.getElementById("pdfCanvas"),
  overlay: document.getElementById("overlay"),
  viewportLoader: document.getElementById("viewportLoader"),
  viewportLoaderText: document.getElementById("viewportLoaderText"),
  signCanvas: document.getElementById("signCanvas"),
  clearSignBtn: document.getElementById("clearSignBtn"),
};

export const pdfCtx = els.pdfCanvas.getContext("2d");
export const signCtx = els.signCanvas.getContext("2d");
